[pytest]
testpaths = tests
filterwarnings =
    ignore:You defined a `validation_step` but have no `val_dataloader`:UserWarning
    ignore:The 'train_dataloader' does not have many workers which may be a bottleneck:UserWarning
    ignore:You called `self\.log\('train_.*', .*logger=True\)` but have no logger configured:UserWarning
    ignore:Please import `map_coordinates` from the `scipy\.ndimage` namespace:DeprecationWarning
